// sourced from Polygon.com's list of the best games of all Time
//
// https://www.polygon.com/features/2017/11/27/16158276/polygon-500-best-games-of-all-time

module.exports = [
  "Warlords",
  "The Sentinel",
  "Suikoden 2",
  "Manic Miner",
  "Homeworld",
  "Grand Theft Auto 4",
  "Guitar Hero 2",
  "Super Mario World 2: Yoshi's Island",
  "Robotron: 2084",
  "Dragon Warrior",
  "Eve Online",
  "Metroid",
  "Call of Duty 4: Modern Warfare",
  "NetHack",
  "Doom 2",
  "Katamari Damacy",
  "Portal 2",
  "Silent Hill 2",
  "Adventure",
  "Star Wars: Knights of the Old Republic",
  "Guild Wars 2",
  "Space Invaders",
  "Secret of Mana",
  "M.U.L.E.",
  "Habitat",
  "Ultima Online",
  "Dota 2",
  "The Elder Scrolls 5: Skyrim",
  "Burnout 3: Takedown",
  "Super Smash Bros. Melee",
  "Final Fantasy 7",
  "Harvest Moon",
  "League of Legends",
  "Splinter Cell: Chaos Theory",
  "Madden NFL 2005",
  "ESPN NFL 2K5",
  "Pong",
  "Super Mario Galaxy",
  "Chrono Trigger",
  "Grand Theft Auto: San Andreas",
  "GoldenEye 007",
  "Super Mario Galaxy 2",
  "NHL '94",
  "Elite Beat Agents",
  "Civilization 5",
  "SimCity 2000",
  "The Witcher 3: Wild Hunt",
  "Dance Dance Revolution",
  "Half-Life",
  "Football Manager",
  "Mass Effect 2",
  "Dota",
  "Shadow of the Colossus",
  "Quest for Glory: So You Want to Be a Hero",
  "Mother 3",
  "Super Mario Kart",
  "Guitar Hero",
  "The Sims",
  "Halo: Combat Evolved",
  "Wii Sports",
  "Dark Souls",
  "The Legend of Zelda: Ocarina of Time",
  "Diablo 2",
  "Grand Theft Auto 5",
  "Resident Evil 4",
  "Donkey Kong",
  "Super Mario World",
  "Persona 4/Golden",
  "Zork",
  "Gone Home",
  "Spelunky",
  "EarthBound",
  "The Elder Scrolls 3: Morrowind",
  "Journey",
  "NBA Jam",
  "Metal Gear Solid",
  "Dwarf Fortress",
  "Rogue",
  "FIFA 12",
  "Super Mario Bros.",
  "The Legend of Zelda: A Link to the Past",
  "Civilization 2",
  "Castlevania: Symphony of the Night",
  "Portal",
  "Super Mario 64",
  "SimCity",
  "Half-Life 2",
  "StarCraft",
  "Grand Theft Auto 3",
  "Final Fantasy 6",
  "Super Metroid",
  "Street Fighter 2",
  "Minecraft",
  "World of Warcraft",
  "Ms. Pac-Man",
  "Pokemon Red and Blue",
  "Doom",
  "The Legend of Zelda",
  "Super Mario Bros. 3",
  "Tetris",
  "30 Flights Of Loving",
  "Halo 3",
  "Overwatch",
  "Mario Kart 64",
  "Xcom: Enemy Unknown",
  "Final Fantasy 9",
  "Dragon's Dogma",
  "Star Wars: X-wing Vs. Tie Fighter",
  "Pokemon Gold And Silver",
  "Sonic The Hedgehog",
  "Command And Conquer",
  "Myst",
  "P.t.",
  "Left 4 Dead",
  "Fallout 3",
  "City Of Heroes",
  "Rez/rez Infinite",
  "Starcraft 2: Wings Of Liberty",
  "Warcraft 3: Reign Of Chaos",
  "Vagrant Story",
  "Ultima Underworld: The Stygian Abyss",
  "Star Wars: Tie Fighter",
  "The Secret Of Monkey Island",
  "The Last Of Us",
  "System Shock 2",
  "Superhot Vr",
  "Streets Of Rage 2",
  "Star Wars: The Arcade Game",
  "Spacewar!",
  "Red Faction: Guerilla",
  "Planescape Torment",
  "Phantasy Star 4: The End Of The Millennium",
  "Monster Hunter 4 Ultimate",
  "Homeworld 2",
  "Giants: Citizen Kabuto",
  "Galaga",
  "Fs1 Flight Simulator",
  "Dragon Quest 8: Journey Of The Cursed King",
  "Defender",
  "Defcon",
  "Crusader Kings 2",
  "Civilization 4",
  "Castlevania: Aria Of Sorrow",
  "Brothers: A Tale Of Two Sons",
  "80 Days",
  "Assassin's Creed 2",
  "Pac-man: Championship Edition Dx",
  "Geometry Wars",
  "The Walking Dead Season 1",
  "Metroid Prime",
  "Soulcalibur 2",
  "Animal Crossing: New Leaf",
  "Super Mario 3d World",
  "Wolfenstein 3d",
  "Mortal Kombat 2",
  "Team Fortress 2",
  "The Legend Of Zelda: Link's Awakening",
  "Unreal Tournament",
  "The Operative: No One Lives Forever",
  "Super Smash Bros.",
  "Everquest",
  "The Oregon Trail",
  "Resident Evil",
  "Phantasy Star Online",
  "Kirby's Adventure",
  "Hearthstone",
  "Street Fighter 3: Third Strike",
  "Kirby: Canvas Curse",
  "Vampire The Masquerade - Redemption",
  "Her Story",
  "Undertale",
  "Rock Band",
  "Dune 2: The Building Of A Dynasty",
  "Cart Life",
  "Uncharted 2: Among Thieves",
  "Mike Tyson's Punch Out!!",
  "Rock Band 2",
  "Diablo",
  "Quake",
  "Frog Fractions",
  "Device 6",
  "The Legend Of Zelda: The Wind Waker",
  "Mario Kart 8",
  "Gunstar Heroes",
  "Call Of Duty 2",
  "Bioshock",
  "Herzog Zwei",
  "Prince Of Persia: The Sands Of Time",
  "Sid Meier's Railroad Tycoon",
  "Hitman: Blood Money",
  "Counter-strike",
  "Kentucky Route Zero",
  "Super Mario Maker",
  "Papers, Please",
  "Final Fantasy Tactics",
  "Grand Theft Auto: Vice City",
  "Burnout Paradise",
  "Elite",
  "Tony Hawk's Pro Skater 2",
  "Metal Gear Solid 2: Sons Of Liberty",
  "Microsoft Flight Simulator",
  "The Legend Of Zelda: A Link Between Worlds",
  "Diablo 3",
  "Thief: Deadly Shadows",
  "The World Ends With You",
  "Super Mario Bros. 2",
  "Sonic Cd",
  "Proteus",
  "Nba 2k12",
  "God Hand",
  "Final Fantasy",
  "Combat",
  "Tennis For Two",
  "Assassin's Creed 4: Black Flag",
  "Kingdom Hearts",
  "Kirby's Dreamland",
  "Forza Horizon 3",
  "Gauntlet",
  "Super Mario Sunshine",
  "Max Payne",
  "Ico",
  "Dark Souls 2",
  "Wasteland",
  "Ultima 7: The Black Gate",
  "The Stanley Parable",
  "Tenchu: Stealth Assassins",
  "Snake",
  "Shadow Hearts: Covenant",
  "Quake 3: Arena",
  "Phoenix Wright: Ace Attorney",
  "Mvp Baseball 2005",
  "Marvel Vs. Capcom 2: New Age Of Heroes",
  "Heroes Of Might And Magic 3",
  "Fatal Frame 2: Crimson Butterfly",
  "Event[0]",
  "Demon Attack",
  "Sonic The Hedgehog 2",
  "Fez",
  "Age Of Empires 2",
  "Demon's Souls",
  "Persona 3",
  "Bloodborne",
  "Final Fantasy 8",
  "Inside",
  "Donkey Kong Country",
  "The Hitchhiker's Guide To The Galaxy",
  "King's Quest",
  "Star Control",
  "Maniac Mansion",
  "Pokemon Go!",
  "Fallout",
  "Castlevania 3: Dracula's Curse",
  "The Jackbox Party Pack",
  "Castlevania",
  "Another World",
  "Psychonauts",
  "Asteroids",
  "Devil May Cry 3: Dante's Awakening",
  "Gears Of War",
  "Shenmue",
  "X-com: Ufo Defense",
  "Wing Commander",
  "Shantae And The Pirate's Curse",
  "Sensible Soccer",
  "Monster Hunter Generations",
  "Impossible Mission",
  "Flashback",
  "Dishonored",
  "Mass Effect",
  "Tomb Raider",
  "Soulcalibur",
  "Halo 2",
  "Jet Grind Radio",
  "Left 4 Dead 2",
  "Warcraft 2: Tides Of Darkness",
  "Virtua Racing",
  "Red Dead Redemption",
  "Monkey Island 2: Lechuck's Revenge",
  "Gran Turismo",
  "A Mind Forever Voyaging",
  "Tony Hawk's Pro Skater",
  "Doom",
  "Burnout Revenge",
  "Zero Escape: Virtue's Last Reward",
  "Warioware: Twisted!",
  "Tony Hawk's Underground",
  "Super Mario 3d Land",
  "Street Fighter Alpha 3",
  "Star Raiders",
  "Mini Metro",
  "Batman: Arkham Asylum",
  "Stardew Valley",
  "Metal Gear Solid 5: The Phantom Pain",
  "Mega Man X",
  "Warioware, Inc.: Mega Microgames!",
  "Virtua Fighter 2",
  "Metal Gear Solid 3: Snake Eater",
  "Fallout: New Vegas",
  "Bushido Blade 2",
  "Animal Crossing",
  "Mirror's Edge",
  "Braid",
  "Shovel Knight",
  "Frogger",
  "Nights Into Dreams...",
  "Wizardry: Proving Grounds Of The Mad Overlord",
  "Uridium",
  "Syberia",
  "Stephen's Sausage Roll",
  "Silent Hill",
  "Pillars Of Eternity",
  "Mega Man 2",
  "Koronis Rift",
  "Jumpman Junior",
  "International Karate +",
  "God Of War 2",
  "Fire Emblem Awakening",
  "Fallout 2",
  "Devil's Crush",
  "Hunt The Wumpus",
  "Crazy Taxi",
  "Beatmania",
  "Ant Attack",
  "Mortal Kombat",
  "Lumines",
  "Metal Gear Solid Guns Of The Patriots",
  "Prince Of Persia",
  "Paper Mario: The Thousand Year Door",
  "Daytona Usa",
  "Ftl: Faster Than Light",
  "Star Wars: X-wing",
  "Ultima Quest Of The Avatar",
  "Super Mario Land Six Golden Coins",
  "Pokemon X And Y",
  "Parappa The Rapper",
  "Limbo",
  "Lemmings",
  "Castle Crashers",
  "Joust",
  "Contra The Alien Wars",
  "Super Bomberman",
  "Fantastic Contraption",
  "Far Cry 2",
  "Valkyria Chronicles",
  "Balance Of Power",
  "Stunt Car Racer",
  "Rocket League",
  "Return To Castle Wolfenstein",
  "Panzer Dragoon Orta",
  "Call Of Duty",
  "I Have No Mouth, And I Must Scream",
  "Forza Motorsport 4",
  "Tony Hawk's Pro Skater 3",
  "Max Payne 2",
  "Hitman",
  "Bastion",
  "Fruit Ninja",
  "Rollercoaster Tycoon",
  "Ninja Gaiden",
  "Dungeons And Dragons: Pool Of Radiance",
  "Dead Space",
  "Bayonetta 2",
  "Yakuza 0",
  "Threes",
  "Quadrilateral Cowboy",
  "Dishonored 2",
  "Populous",
  "Hot Shots Golf",
  "Deus Ex",
  "The Legend Of Zelda: Majora's Mask",
  "Samurai Shodown",
  "Puzzle Quest",
  "Panzer Dragoon 2 Zwei",
  "Miner 2049er",
  "Marvel Vs. Capcom: Clash Of Super Heroes",
  "Lunar Lander",
  "Gunpoint",
  "Gran Trak 10",
  "God Of War",
  "Empire: Total War",
  "Dungeon Keeper",
  "Stubbs The Zombie In Rebel Without A Pulse",
  "Descent",
  "Computer Space",
  "Battlezone",
  "Ikaruga",
  "Paradroid",
  "Breakout",
  "Super Smash Bros. Brawl",
  "Battlefield 1942",
  "Towerfall",
  "Flower",
  "Chrono Cross",
  "Split/second",
  "Gran Turismo A-spec",
  "Age Of Empires",
  "Tekken 3",
  "Tempest 2000",
  "Day Of The Tentacle",
  "Resident Evil 2",
  "Mirror's Edge",
  "Braid",
  "Shovel Knight",
  "Frogger",
  "Nights Into Dreams...",
  "Wizardry: Proving Grounds Of The Mad Overlord",
  "Uridium",
  "Syberia",
  "Stephen's Sausage Roll",
  "Silent Hill",
  "Pillars Of Eternity",
  "Mega Man 2",
  "Koronis Rift",
  "Jumpman Junior",
  "International Karate +",
  "God Of War 2",
  "Fire Emblem Awakening",
  "Fallout 2",
  "Devil's Crush",
  "Hunt The Wumpus",
  "Crazy Taxi",
  "Beatmania",
  "Ant Attack",
  "Mortal Kombat",
  "Lumines",
  "Metal Gear Solid Guns Of The Patriots",
  "Prince Of Persia",
  "Paper Mario: The Thousand Year Door",
  "Daytona Usa",
  "Ftl: Faster Than Light",
  "Star Wars: X-wing",
  "Ultima Quest Of The Avatar",
  "Super Mario Land Six Golden Coins",
  "Pokemon X And Y",
  "Parappa The Rapper",
  "Limbo",
  "Lemmings",
  "Castle Crashers",
  "Joust",
  "Contra The Alien Wars",
  "Super Bomberman",
  "Fantastic Contraption",
  "Far Cry 2",
  "Valkyria Chronicles",
  "Balance Of Power",
  "Stunt Car Racer",
  "Rocket League",
  "Return To Castle Wolfenstein",
  "Panzer Dragoon Orta",
  "Call Of Duty",
  "I Have No Mouth, And I Must Scream",
  "Forza Motorsport 4",
  "Tony Hawk's Pro Skater 3",
  "Max Payne 2",
  "Hitman",
  "Bastion",
  "Fruit Ninja",
  "Rollercoaster Tycoon",
  "Ninja Gaiden",
  "Dungeons And Dragons: Pool Of Radiance",
  "Dead Space",
  "Bayonetta 2",
  "Yakuza 0",
  "Threes",
  "Quadrilateral Cowboy",
  "Dishonored 2",
  "Populous",
  "Hot Shots Golf",
  "Deus Ex",
  "The Legend Of Zelda: Majora's Mask",
  "Samurai Shodown",
  "Puzzle Quest",
  "Panzer Dragoon 2 Zwei",
  "Miner 2049er",
  "Marvel Vs. Capcom: Clash Of Super Heroes",
  "Lunar Lander",
  "Gunpoint",
  "Gran Trak 10",
  "God Of War",
  "Empire: Total War",
  "Dungeon Keeper",
  "Stubbs The Zombie In Rebel Without A Pulse",
  "Descent",
  "Computer Space",
  "Battlezone",
  "Ikaruga",
  "Paradroid",
  "Breakout",
  "Super Smash Bros. Brawl",
  "Battlefield 1942",
  "Towerfall",
  "Flower",
  "Chrono Cross",
  "Split/second",
  "Gran Turismo A-spec",
  "Age Of Empires",
  "Tekken 3",
  "Tempest 2000",
  "Day Of The Tentacle",
  "Resident Evil 2",
  "Ballblazer",
  "Arkanoid",
  "Advance Wars Black Hole Rising",
  "Dragon Age: Inquisition",
  "Super Meat Boy",
  "F-zero",
  "Wipeout",
  "Bully",
  "Catherine",
  "Metroid Return Of Samus",
  "Alone In The Dark",
  "Spider-man 2",
  "Space Channel 5",
  "Cave Story",
  "Ori And The Blind Forest",
  "Fable 2",
  "Star Fox 64",
  "Company Of Heroes",
  "Batman: Arkham City",
  "Garry's Mod",
  "Qwop",
  "Splatoon",
  "Marble Madness",
  "Nine Hours, Nine Persons, Nine Doors (999)",
  "Gravity Rush",
  "Borderlands",
  "Monument Valley",
  "Firewatch",
  "Aladdin",
  "Earth Defense Force 2017",
  "Peggle",
  "Ninja Gaiden",
  "Timesplitters 2",
  "Railroad Tycoon",
  "Depression Quest",
  "Medal Of Honor",
  "The Chronicles Of Riddick: Escape From Butcher Bay",
  "Donkey Kong Jr.",
  "Zelda The Adventure Of Link",
  "River City Ransom",
  "Picross 3d",
  "Paper Mario",
  "Electroplankton",
  "Plants Vs. Zombies",
  "Cities: Skylines",
  "Boulder Dash",
  "Archon: The Light And The Dark",
  "Dragon Age: Origins",
  "Angry Birds",
  "The Witcher Assassins Of Kings",
  "Professor Layton And The Unwound Future",
  "Hitman Go",
  "Final Fantasy 10",
  "Bioshock 2",
  "Sonic Colors",
  "Vanquish",
  "Wolfenstein: The New Order",
  "Psi-ops: The Mindgate Conspiracy",
  "Jetpack Joyride",
  "Mario Paint",
  "Super Castlevania 4",
  "Need For Speed: Most Wanted",
  "Kerbal Space Program",
  "Wwf No Mercy",
  "Devil May Cry",
  "Indiana Jones And The Fate Of Atlantis",
  "Kim Kardashian: Hollywood",
  "Galaxian",
  "Double Dragon",
  "Street Fighter 4",
  "Fallout 4",
  "Nidhogg",
  "Bejeweled",
  "Snatcher",
  "Sam & Max Hit The Road",
  "Qix",
  "Power Stone 2",
  "Just Cause 2",
  "Pole Position",
  "Missile Command",
  "Military Madness",
  "Metro 2033",
  "Fire Emblem Fates",
  "Final Fantasy 14",
  "Alpha Centauri",
  "Grim Fandango",
  "The Elder Scrolls Oblivion",
  "Rhythm Heaven",
  "Drop7",
  "Kingdom Rush",
  "Power Stone",
  "Legacy Of Kain: Soul Reaver",
  "Command And Conquer: Red Alert",
  "Destiny",
  "Metal Gear Solid: Peace Walker",
  "Deus Ex Machina",
  "Thief: The Dark Project",
  "Star Wars Knights Of The Old Republic The Sith Lords",
  "Tiger Woods Pga Tour 12",
  "Littlebigplanet"
];